-- 第一批：创建主表
CREATE TABLE reddit_ai_posts (
    id TEXT PRIMARY KEY,
    permalink TEXT NOT NULL,
    url TEXT,
    title TEXT NOT NULL,
    selftext TEXT,
    selftext_html TEXT,
    score INTEGER DEFAULT 0,
    upvote_ratio REAL DEFAULT 0,
    num_comments INTEGER DEFAULT 0,
    total_awards_received INTEGER DEFAULT 0,
    num_crossposts INTEGER DEFAULT 0,
    author TEXT,
    subreddit TEXT NOT NULL,
    subreddit_subscribers INTEGER,
    created_utc INTEGER NOT NULL,
    quality_score REAL DEFAULT 0,
    content_category TEXT,
    tech_relevance_score REAL DEFAULT 0,
    ai_category TEXT,
    processed_at INTEGER DEFAULT (unixepoch()),
    extraction_status TEXT DEFAULT 'pending',
    last_updated INTEGER DEFAULT (unixepoch()),
    is_self BOOLEAN DEFAULT 0,
    is_video BOOLEAN DEFAULT 0,
    over_18 BOOLEAN DEFAULT 0,
    locked BOOLEAN DEFAULT 0,
    stickied BOOLEAN DEFAULT 0,
    crawl_timestamp INTEGER DEFAULT (unixepoch()),
    crawl_date TEXT GENERATED ALWAYS AS (date(crawl_timestamp, 'unixepoch')) STORED,
    crawl_source TEXT DEFAULT 'auto',
    api_version TEXT DEFAULT 'v1',
    UNIQUE(id, crawl_date)
);
