name: Scheduled Reddit Crawl

on:
  schedule:
    # 每天UTC 2:00 (北京时间10:00) 执行
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      force_run:
        description: '强制执行爬取任务'
        required: false
        default: 'false'
        type: boolean

jobs:
  trigger-crawl:
    runs-on: ubuntu-latest
    name: Trigger Reddit Crawl
    steps:
      - name: Trigger Cloudflare Worker
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"force": "${{ github.event.inputs.force_run || false }}"}' \
            "${{ secrets.CRAWLER_WEBHOOK_URL }}/crawl"
        continue-on-error: true
      
      - name: Check crawl status
        run: |
          sleep 30
          curl -X GET \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            "${{ secrets.CRAWLER_WEBHOOK_URL }}/stats"

  notify-status:
    runs-on: ubuntu-latest
    name: Notify Status
    needs: trigger-crawl
    if: always()
    steps:
      - name: Notify Success
        if: needs.trigger-crawl.result == 'success'
        run: |
          echo "✅ Reddit爬取任务执行成功"
          # 这里可以添加通知逻辑，比如发送邮件或Slack消息
      
      - name: Notify Failure
        if: needs.trigger-crawl.result == 'failure'
        run: |
          echo "❌ Reddit爬取任务执行失败"
          # 这里可以添加失败通知逻辑
